### ISSUE TITLE
Duplicate key in inventory editor

### ISSUE THREAD

**Issue by evilwombat** [supremetakoyaki/Scramble#2]
Hey hey. Nice work! I've been using this for some time, but I'm running into the following error, on v0.8x:

`System.ArgumentException: An item with the same key has already been added. Key: 1
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Scramble.Classes.InventoryPin.IntersectEquippingData(Dictionary`2 EquippingData)
   at Scramble.Forms.PinInventoryEditor.Serialize()
   at Scramble.Forms.PinInventoryEditor..ctor()
   at Scramble.ScrambleForm.OpenInvEditorButton_Click(Object sender, EventArgs e)
`

I may be able to look at this tomorrow, but unfortunately this program uses .NET 5.0 and can only be used on Windows. I am on Linux, and Mono will only work with .NET 4.8. So you will probably beat me to a solution. Thanks again!

**Comment by supremetakoyaki** [comment]
Hi there. If you can send me your save, that'd be super.

**Comment by OnyxMemory** [comment]
Hey I'm having a similar issue. Everytime I open the pin editor i get this error.

I've attached my save as well (changed to txt so github will allow the upload): 
[neotwewysave.txt](https://github.com/supremetakoyaki/Scramble/files/7069804/neotwewysave.txt)


```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: An item with the same key has already been added. Key: 2
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Scramble.Classes.SaveData.WhosEquippingThisPin(Int32 PinIndex)
   at Scramble.Forms.PinInventoryEditor.Serialize()
   at Scramble.Forms.PinInventoryEditor..ctor()
   at Scramble.ScrambleForm.OpenInvEditorButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Private.CoreLib.dll
----------------------------------------
Scramble
    Assembly Version: 0.8.1.0
    Win32 Version: 0.8.1.0
    CodeBase: file:///D:/Downloads/scramble2/Scramble.dll
----------------------------------------
System.Runtime
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 5.0.9.0
    Win32 Version: 5.0.921.36302
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.9/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 5.0.9.0
    Win32 Version: 5.0.921.36302
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.9/System.Windows.Forms.Primitives.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 5.0.0.2
    Win32 Version: 5.0.421.11614
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.9/System.Drawing.Common.dll
----------------------------------------
System.Threading
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Collections.dll
----------------------------------------
ntwewy-db
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3
    CodeBase: file:///D:/Downloads/scramble2/ntwewy-db.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.ComponentModel.TypeConverter.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 5.0.921.36302
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.9/Accessibility.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.ComponentModel.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Runtime.Extensions.dll
----------------------------------------
System.Memory
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Memory.dll
----------------------------------------
System.IO.FileSystem
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.IO.FileSystem.dll
----------------------------------------
System.Buffers
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Buffers.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.9/System.Resources.Extensions.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/netstandard.dll
----------------------------------------
System.Drawing
    Assembly Version: 5.0.9.0
    Win32 Version: 5.0.921.36302
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.9/System.Drawing.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Net.WebClient.dll
----------------------------------------
System.Net.WebHeaderCollection
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Net.WebHeaderCollection.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Private.Uri.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.9/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Net.Requests
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Net.Requests.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Net.Primitives.dll
----------------------------------------
System.Net.Http
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Net.Http.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Diagnostics.Tracing.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Collections.NonGeneric.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Collections.Concurrent.dll
----------------------------------------
System.Net.ServicePoint
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Net.ServicePoint.dll
----------------------------------------
System.Net.Security
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Net.Sockets.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Net.NameResolution.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Security.Claims.dll
----------------------------------------
System.Security.Cryptography.Encoding
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Security.Cryptography.Encoding.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Threading.ThreadPool.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Linq
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Linq.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.ObjectModel.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.921.35908
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************

**Comment by supremetakoyaki** [comment]
Will be "fixed" in the next release.
In the meantime, go to the pin menu in-game, and unequip any duplicate pin you have within the same deck.

In your case @OnyxMemory , unequip one of these two:
![image](https://user-images.githubusercontent.com/9308209/131199421-f07e96ac-543d-4e89-a88d-df3026caef24.png)

Then save and try loading the save file.
